# Generated by Django 2.2 on 2019-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='제목 없음', max_length=50)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
