# Generated by Django 2.2.1 on 2019-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
    ]
