# Generated by Django 2.2.1 on 2019-05-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0003_auto_20190507_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
    ]
