# Generated by Django 2.1.7 on 2019-08-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0004_auto_20190507_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='kakao',
            field=models.CharField(default='kakao', max_length=50),
        ),
    ]
